version: '3.4'
services:
  temptunes:
    build:
      context: ./
      dockerfile: Dockerfile
    image: temptunes
    ports:
      - "8080:8080"
    networks:
      - temptunesnetwork
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - temptunesnetwork

networks:
  temptunesnetwork: